name: kas_go
description: "Aplikasi transparansi dan pencatatan kas Karang Taruna modern."
publish_to: "none"
version: 1.0.5+6

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management & Routing
  flutter_riverpod: ^2.5.1
  go_router: ^14.0.0

  # Local Database (SQLite via Drift)
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0

  # Charts
  fl_chart: ^0.67.0

  # Firebase (Spark tier)
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

  # Networking & Utilities
  http: ^1.2.1
  url_launcher: ^6.2.6
  intl: ^0.19.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  drift_dev: ^2.16.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/banners/
